-- ============================================
-- ProjectHub EF Core Initial Tables for Neon
-- ============================================

-- Migration history table
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Clients table
CREATE TABLE IF NOT EXISTS "Clients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ModifiedAt" timestamp with time zone
);

-- Projects table
CREATE TABLE IF NOT EXISTS "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Budget" numeric NOT NULL,
    "StartDate" date NOT NULL,
    "DueDate" date NOT NULL,
    "InitialStatus" integer NOT NULL,
    "PriorityLevel" integer NOT NULL,
    "Progress" integer NOT NULL,
    "ClientId" integer NOT NULL REFERENCES "Clients"("Id") ON DELETE CASCADE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ModifiedAt" timestamp with time zone
);

-- Index for project client
CREATE INDEX IF NOT EXISTS "IX_Projects_ClientId" ON "Projects" ("ClientId");

-- Users table
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "Role" integer NOT NULL DEFAULT 0
);

-- RefreshTokens table
CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Token" text NOT NULL,
    "UserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL
);

-- Index for refresh tokens
CREATE INDEX IF NOT EXISTS "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

-- Optional: record last migration so EF Core doesn't try to re-run it
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251202120938_Neon', '9.0.8');
